services:
  sportfar-backend:
    build: .
    container_name: sportfar-backend
    environment:
      DB_PORT: ${MYSQL_PORT}
      DB_HOST: ${MYSQL_HOST}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      PORT: ${BACKEND_PORT}
    ports:
      - "3000:3000"
